#!/bin/bash

#input is the output generated by get_lottozahln.sh
#generate two new files:

source config

#all lottozahlen without superzahl
echo "--extracting rows without superzahl"
#get all lottozahlen without SZ and strip some columns
grep "$DummySZ" $1 | cut -d\  -f 2-8 > $1_ohne_SZ
sed -i -e 's/$/ /' $1_ohne_SZ

#all lottozahlen with superzahl
echo "--extracting rows with superzahl"
#get all lottozahlen with SZ and strip some columns
grep -v "$DummySZ" $1 | cut -d\  -f 2-9 > $1_mit_SZ
sed -i -e 's/$/ /' $1_mit_SZ

