#!/bin/bash

#input is the output generated by get_lottozahln.sh
#generate two new files:
#  one with all lottozahlen but without superzahl
#  another with all lottozahlen that have a superzahl

source config

#all lottozahlen with superzahl stripped
echo "--stripping superzahl"
cut -d\  -f 2-8 $1 > $1_stripped

#all lottozahlen with superzahl
echo "--stripping rows without superzahl"
grep -v "$DummySZ" $1 > $1_SZ

