#!/bin/bash

page=http://www.lottozahlenonline.de/statistik/lotto-am-samstag/lottozahlen-archiv.php?j=

function getYears {
  echo {1955..2014}
}

##$1=class name
function extract {
  sed -n "s|<div class=\"${1}\">\([^<]*\)</div>|\1 |pg"
}

function grepDivs {
  grep -oP '<div class="zahlensuche_nr">[0-9]+</div><div class="zahlensuche_datum">[0-9]{2}\.[0-9]{2}\.[0-9]{4}</div>(<div class="zahlensuche_zahl">[0-9]*</div>){6}<div class="zahlensuche_zz">[0-9]*</div>'
}

function splitDivs {
  extract zahlensuche_nr | extract zahlensuche_datum | extract zahlensuche_zahl | extract zahlensuche_zz
}

##$1=year
function readLottoZahlen {
  echo "--loading ${page}${1}"
  line=$(wget $page$1 -qO- | tr -d "\n" | grepDivs | splitDivs)
  echo "${line}\n" 
  echo "${line}\n" > lotto/$1
}

function getNumbers {
  for y in $(getYears)
  do
	wget http://www.lottozahlenonline.de/statistik/beide-spieltage/lottozahlen-archiv.php?j=$y -qO- | tr -d '\n' > tmp/whole

	cat tmp/whole | grep -oP '<div class="zahlensuche_nr">[^<]*</div><div class="zahlensuche_datum"[^<]*</div>(<div class="zahlensuche_zahl">[^<]*</div>){6}<div class="zahlensuche_zz">[^<]*</div>' > tmp/divs

	cat tmp/divs | sed 's|</div>| |g' |
               sed 's|<div class="zahlensuche_nr">| |g' |
               sed 's|<div class="zahlensuche_datum">| |g' |
               sed 's|<div class="zahlensuche_zahl">| |g' |
               sed 's|<div class="zahlensuche_zz">| |g' > tmp/data

	cat tmp/data | sed -e 's/ //' -e 's/\s\([0-9\]\)\s/ 0\1 /g' -e 's/  / /g'
  done

}

function main {
  mkdir -p lotto
  rm lotto/*
  for y in $(getYears)
  do
    readLottoZahlen $y
  done
  getNumbers
}

getNumbers
